from selenium.webdriver.common.by import By
class sourcepath:
    SUCESSPATH=(By.XPATH,"//div[@class='ajs-message ajs-success ajs-visible']")
    HOVER_BUTTON = (By.XPATH, "//a[@class='sc-iHhHRJ cKagkC']")
    CLOUDX_BUUTON = (By.XPATH, "//a[@class='sc-iHhHRJ cKagkC']//a[1]")
    PLAYOUTDASHBOARD = (By.XPATH, "//div[@class='playoutChannelDashboard-label']")
    RECASTERPAGE = (By.XPATH, "//a[@href='/recaster']")
    CLOUDX_HOVER_BUTTON = (
        By.XPATH, "//div[contains(@class,'w3-row channelMenuBar')]/div[contains(@class,'l13 m24 s24 w3-col')]/div[3]")
    CLOUDX_TO_RECASTER_BUTTON = (By.XPATH, "//body[1]/div[4]/div[1]/div[3]/div[3]/div[1]/div[1]/ul[1]/li[2]/a[1]")
    RECASTER_HOVER_BUTTON = (By.XPATH, "//*[@id='menues']/li[3]")
    RECASTERPAGE_TO_CLOUDX = (By.XPATH, "//a[normalize-space()='CloudX']")
    CLOUDX_SHOW_LOGOUT_BUTTON = (
        By.XPATH, "//div[@class='d-flex w3-row w3-right textCapitalize align-items-center dropdown hoverText']")
    CLOUDX_LOGOUT_BUTTON = (By.XPATH, "//a[@title='Logout']")
    # RECASTER_SHOW_LOGOUT_BUTTON = (By.XPATH, "//div[@class='media']")
    RECASTER_LOGOUT_BUTTON = (By.XPATH, "/html/body/header/div/div/nav/div[2]/ul/li/a")
    SHOW_LOGOUT_BUTTON = (By.XPATH, "//div[@class='media']")
    LOGOUT_BUTTON = (By.XPATH, "//div[@class='sc-kgAjT jRpQlR selectable item ']")
    LOGIN_SUCESS_MESSAGE = (By.XPATH, "//p[@class='heading']")
    Filemenu = (By.XPATH, "//div[@id='namedMenuLeft']/div[contains(text(), 'File')]")
    EDITMENU = (By.XPATH, "//div[@id='namedMenuLeft']/div[contains(text(), 'Edit')]")
    VIEWMENU = (By.XPATH, "//div[@id='namedMenuLeft']/div[contains(text(), 'View')]")
    TOOLSMENU = (By.XPATH, "//div[@id='namedMenuLeft']/div[contains(text(), 'Tools')]")
    PLAYOUTMENU = (By.XPATH, "//div[@id='namedMenuLeft']/div[contains(text(), 'Playout')]")
    LOADPLAYLISTBUTTON = (By.XPATH, "//p[normalize-space()='Load New Playlist']")
    LOADPLAYLISTBUTTONTEXT = (By.XPATH, "//div[contains(text(),'Load Playlist')]")
    COUNTPLAYLIST = f"//*[contains(@class, 'flex-fill plListCard')]"  # (By.XPATH, "//div[@class='flex-fill plListCard']")
    NUMBEROFCOUNT = (By.XPATH, "//div[@id='plFound']")
    BACKBUTTON = (By.XPATH, "//button[@title='Back']")
    STOPBUTTON = (By.XPATH, "//button[@id='btnStop']")
    REQUESTADMIN = (By.XPATH, "//a[@onclick='accessAsAdmin(this)']")
    EDITBUTTON = (By.XPATH, "//div[@class='w3-col l6 m6 s12']//div[2]")
    DELETEALLBUTTON = (By.XPATH, "//p[normalize-space()='Delete All']")
    TEXTNOTPLAYLISTEXIT = (By.XPATH, "//p[contains(@class,'px16')]")
    STOPYES = (By.XPATH, "//button[@id='yesBtn']")
    CHEKCONAIR = (By.XPATH, "//div[@id='readyId']")
    CHECKACCESS = (By.XPATH,"//div[@title='Edit Mode']")
    STARTPLAY =(By.XPATH,"//button[@id='btnPlay']")
    APPENBUTTON = (By.XPATH,"//p[@data-action='apend_playlist']")
    APPENPOPUP =(By.XPATH,"//div[contains(text(),'Load Playlist')]")
    DELETEAPPENBTN= (By.XPATH,"//p[@onclick='buildLoadedPlaylist()']")